### ISSUE TITLE
[Feature Request] Fold All Items at Given Heading Level

### ISSUE THREAD

**Issue by ossie-git** [shushcat/vim-minimd#3]
First of all, I'd like to thank you for developing this fantastic plugin. I just installed it today and I can't believe I hadn't run into it before.

I had a small feature request. Would it be possible to have add some type of option to fold all the sections. For example, if I have a document with several Heading 1 items and I wanted to close all of them so I only saw them and nothing else, would that be possible? Or to tell it to show me Heading 2 and Heading 1 level entries only? Thanks

**Comment by shushcat** [comment]
This suggestion is in line with something I've been meaning to do for a while, namely to write a function to simultaneously toggle folding for all headers in a buffer.  I have found display of all headers at a specified level to be best (for my needs) provided by a series of commands   for [fzf](https://github.com/junegunn/fzf); these commands are present [in my dotfiles](https://github.com/shushcat/smalldots/blob/master/_vim/plugin/fzf.vim)---specifically, the [`s:header_lines` function](https://github.com/shushcat/smalldots/blob/765d8dc48695338c0fcf2388c9ae14b11b3071ea/_vim/plugin/fzf.vim#L27) and the [`FZFHLines` command](https://github.com/shushcat/smalldots/blob/765d8dc48695338c0fcf2388c9ae14b11b3071ea/_vim/plugin/fzf.vim#L80) implement that functionality.  I have been leery of adding those bits of code to this plugin since that would add some complexity to something that is, by design, as simple as I can possibly keep it.

I'll put together a sensible buffer-wide folding command that uses the folding function I've already implemented, and will think a bit more about whether or not the `fzf` commands should be added.

**Comment by shushcat** [comment]
As of ea028e8880f7ca0d70178f8878ba569303337cfd, all headers of a specified level _n_ can be folded with the command _n_-`Space`.

**Comment by ossie-git** [comment]
Fantastic. Thanks a lot. Just found a small bug. If the last line of the file is a header, it isn't affected by the new folding behavior. Adding an empty line after it allows it to be detected correctly

**Comment by shushcat** [comment]
Neglecting to fold 'empty' headers is part of the plugin design.  One way to think of it is that if there's nothing in the header, there's nothing to fold :)
