### ISSUE TITLE
Move or disable wordcount

### ISSUE THREAD

**Issue by BigBlackDog** [shushcat/vim-minimd#8]
I wonder if it would be a good idea to implement some kind of guard to prevent your fabulous plugin from changing the statusbar for markdown files.

I use [lualine](https://github.com/nvim-lualine/lualine.nvim) to display the statusbar, but whenever I edit a markdown file minimd takes over and all the fancy stuff is gone :)

I'm thinking of something like setting a variable like `let g:minimd_leave_statusbar_untouched = 1` which will be evaluated wherever necessary.

**Comment by shushcat** [comment]
That's a good idea---I've been wondering about the usefulness of the word count in the status bar, and have myself settled on using separate functions for tracking word count goals.  Those functions produce a small popup window that disappears when navigating away from the buffer for which the goal is set, and which is cleared when the goal is reached.  I will think about it a bit, and will either remove the statusbar word count from this plugin (adding it to a separate plugin for tracking word counts) or will add the word count goal function along with switches to control whether and where the counts are displayed.

**Comment by shushcat** [comment]
As of e998040, I've removed the word count functionality (along with the associated tampering with the statusline) since a word count can be displayed with `g Ctrl-g`.  I've split off the word count goal functions from my personal Vim configuration, and will maintain them at [this repository](https://github.com/shushcat/vim-wc-goal), should anyone be interested.
